Updated lk_env.h to resolve compilation error
NREL/SAM pull request #1005
Opened 2022-04-18 16:31 UTC by dakotaramos

# Pull Request Template

## Description

Updated line 64 to resolve compilation error during conversion of string when installing SAM / PySAM as developer. 
If this should be merged into a different branch, please let me know.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-04-30 10:01 UTC, sjanzou requested changes
Change long_name and desc to be consistent with config change (.ToStdString()).

2022-05-02 15:16 UTC, dakotaramos commented
@sjanzou updated long_name and desc per your review in latest commit. Please let me know if you need anything further.

2022-05-03 04:52 UTC, sjanzou approved these changes

2022-05-03 06:10 UTC, sjanzou approved these changes
Thank you for identifying the issue and your contribution!

2022-05-03 06:16 UTC, merged