Fix typo bug in System Sizing macros
NREL/SAM pull request #1115
Opened 2022-08-01 17:44 UTC by luzpaz

## Description

Change variable 'montn' to 'mount'
Note: this fix hasn't been tested

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-08-01 23:26 UTC, cpaulgilman requested changes
@luzpaz Thank you for fixing this! Please also fix the typo `.../macros/PV battery/System Sizing.lk`. 

SAM uses the folder structure to determine what macros are available for each configuration -- a little clumsy, I know...

2022-08-02 00:44 UTC, luzpaz commented
> Please also fix the typo in `.../macros/PV battery/System Sizing.lk`

Other typo?

2022-08-02 15:52 UTC, cpaulgilman approved these changes
This fixes an LK script error with the System Sizing macro for PV and PV-Battery configurations when the module temperature model option is set to **Heat transfer model** with **Integrated** as the mounting configuration:

![image](https://user-images.githubusercontent.com/27711933/182417908-a4506cd3-85c8-4c7d-a5db-1540e8efcdea.png)

2022-08-02 16:13 UTC, luzpaz commented
> Please also fix the typo in `.../macros/PV battery/System Sizing.lk`

@cpaulgilman please clarify, I still don't see the typo you're asking me to fix. I've scoured the graphic to find it unsuccessfully. Can you point it out ?

2022-08-02 17:01 UTC, cpaulgilman commented
> > Please also fix the typo in `.../macros/PV battery/System Sizing.lk`
> 
> @cpaulgilman please clarify, I still don't see the typo you're asking me to fix. I've scoured the graphic to find it unsuccessfully. Can you point it out ?

The typo is fixed in both copies of the script. Thank you.

2022-08-02 17:01 UTC, merged