Etes sco2 dev
NREL/SAM pull request #1368
Opened 2023-03-03 18:09 UTC by qualand

# Pull Request Template

## Description
Changes to sco2 cycle python modeling interface. I cleaned up a few things and added the PHX phase change plotting in the T-s diagram. Also added the sco2 cycle macro to the ETES model.

## Type of change
 New feature (non-breaking change which adds functionality)

2023-03-03 21:01 UTC, tyneises requested changes

2023-03-29 15:56 UTC, qualand commented on samples/CSP/sco2_analysis_python_V2/core/sco2_plots.py
> +            # Plotting Phase Change in HTF
Yes

2023-03-29 17:08 UTC, tyneises approved these changes

2023-03-29 17:11 UTC, qualand commented on samples/CSP/sco2_analysis_python_V2/core/PySSC.py
>  		return self.pdll.ssc_data_set_array( c_void_p(p_data), c_char_p(name),pointer(arr), c_int(count))
reverted PySSC.py changes

2023-03-29 22:22 UTC, merged