Clearance height warnings for bifacial systems
NREL/SAM pull request #1544
Opened 2023-11-02 16:41 UTC by mjprilliman

## Description

-Add red text warning for when the fixed tilt, tracker rotation limit, or monthly tilt could cause ground interference with the specified bifacial ground clearance height
-

Fixes #1088 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-11-02 16:42 UTC, mjprilliman commented
@cpaulgilman Before I move this to other module pages can you test this to see if you like the functionality. I'd prefer this over msgbox warnings as they could pop up often in system design. This won't have any effect on calculations at the moment.

2023-11-02 21:35 UTC, cpaulgilman requested changes
I'm getting a callback error when I enable bifacial for the default Detailed PV / Single Owner case:

```
Could not evaluate callback function:cec_is_bifacial->on_change
[94]: reference to unassigned variable:check_clearance_height
[94]: error: _s
[94]: eval error in statement list
```

2023-11-03 14:45 UTC, mjprilliman commented
> I'm getting a callback error when I enable bifacial for the default Detailed PV / Single Owner case:
> 
> ```
> Could not evaluate callback function:cec_is_bifacial->on_change
> [94]: reference to unassigned variable:check_clearance_height
> [94]: error: _s
> [94]: eval error in statement list
> ```

@cpaulgilman this should be cleaned up now but no rush on the review.

2023-11-03 15:26 UTC, cpaulgilman reviewed
The callback issue is fixed -- thanks. Let me know when this is ready for a full review.

2023-11-03 15:30 UTC, mjprilliman commented
> The callback issue is fixed -- thanks. Let me know when this is ready for a full review.

I believe it's ready for a full review, I will let you come up with better language for the message. I am happy to apply that language to all the pages once you have it.

2023-11-09 22:41 UTC, cpaulgilman commented
Looks good for 1-axis tracking.

A couple of questions:

1. Should there be a check for fixed arrays?
2. Should there also be an SSC check on ground clearance? Right now, it is possible to enter negative values and zero for ground clearance, and SSC is not checking for insufficient clearance.

2023-11-10 17:13 UTC, mjprilliman commented
> Looks good for 1-axis tracking.
> 
> A couple of questions:
> 
> 1. Should there be a check for fixed arrays?
> 2. Should there also be an SSC check on ground clearance? Right now, it is possible to enter negative values and zero for ground clearance, and SSC is not checking for insufficient clearance.

1. For fixed arrays that distance is the distance between the ground and the bottom edge of the module so it would not apply here. 
2. I can add SSC checks in the var table and potentially SSC notices, the actual calculations are not currently accounting ground interference.

2023-11-10 17:29 UTC, cpaulgilman approved these changes

2023-11-10 19:22 UTC, merged