Fix solar resource download geocoding issues
NREL/SAM pull request #1692
Opened 2024-02-08 22:47 UTC by cpaulgilman

# Pull Request Template

## Description

NSRDB downloads from Solar Resource input page was submitting user input string to `geocode()` function, assuming that the geocoding API parses the string to determine if it is a street address, location, name, or lat/lon pair. However, `geocode()` function sends input string to the MapQuest Geocode Address API, which requires a street address or location name as input: https://developer.mapquest.com/documentation/geocoding-api/address/get/.

Items fixed:

* Change geocode function to return latLon instead of displayLatLon to latLon. See MapQuest documentation for justification.
* Update Solar Resource UI callback to not use lat/lon as input geocode function. If user input string appears to be lat/lon, submit that directly to NSRDB instead of geocoding it.
* Update Advanced Download to show lat/lon returned by geocoding function to help with troubleshooting

Note related issues that will be fixed in separate pull requests:
* https://github.com/NREL/SAM/issues/1534
* https://github.com/NREL/SAM/issues/1426

Fixes #1526

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2024-02-08 22:53 UTC, cpaulgilman commented
Testing this requires building SAM-private. to get that to work, I had to modify the SAM-private CMakeLists.txt to comment out the SDK tool settings:

![image](https://github.com/NREL/SAM/assets/27711933/91354357-0484-44d9-bf70-4be027058510)

To run the private version:

1. Build SAMOS. (open source)
2. Clean SAM solution and rebuild. (SAM private)
3. Run SAM.

2024-02-13 07:53 UTC, sjanzou requested changes
For me, SAM-private built without issue using the unmodified CMakeLists.txt in the patch branch.

The more detailed feedback is great:
![image](https://github.com/NREL/SAM/assets/6498311/d9729a41-1383-4c80-afe7-777c3a84b28d)

However, -39,105 creates a callback error:
![image](https://github.com/NREL/SAM/assets/6498311/7b6faaa2-9c29-4ee1-9013-adfa14eb386d)

2024-02-17 00:38 UTC, cpaulgilman commented
Here's a CSV file with a list of location names and lat/lon pairs for places around the world and available NSRDB datasets and and LK script that creates it that might be helpful for testing: [nsrdb-endpoints.zip](https://github.com/NREL/SAM/files/14317138/nsrdb-endpoints.zip)

2024-02-18 08:07 UTC, sjanzou approved these changes
Working for all valid lat/lon tested and for values for which there is no NSRDB data, returns all information we have; e.g.
![image](https://github.com/NREL/SAM/assets/6498311/5dfcb89b-3004-412d-97de-ddef2e273d79)

2024-02-19 16:14 UTC, merged