Price Signal Dispatch
NREL/SAM pull request #371
Opened 2020-08-25 20:15 UTC by brtietz

Merge price signal dispatch algorithm into develop. Should be merged after SSC PR: https://github.com/NREL/ssc/pull/451 .

Changes:
- Split dispatch page from main battery storage page (@cpaulgilman, note: a new help page will be needed)
- Rename "battery cycle costs" to "cycle degradation penalty" in the GUI
- Make the cycle degradation penalty an array so the user can specify a schedule
- Add new dispatch option

Let me know if additional changes are needed to help pages, version upgrade script, or similar.

2020-10-13 16:41 UTC, cpaulgilman approved these changes
This looks good to me, Brian. I agree with Steve that we should merge sooner than later. I pushed an update to startup.lk to point to new Help topics that I will commit later -- I don't want to clutter up this pull request with a bunch of new HTML and PNG Help files.

2020-10-17 21:57 UTC, dguittet requested changes
Looks great! I think this is a welcome change.

Thoughts on naming the UI page?

2020-10-17 21:57 UTC, dguittet commented on deploy/runtime/startup.lk
>  			  { 'sidebar'='Battery Storage', 'help'='battery_storage_btm' } );
@cpaulgilman @brtietz Can I suggest calling this "Battery Cell and System" to align with the battery's SSC group names?

2020-10-17 21:57 UTC, dguittet commented on deploy/runtime/ui/Battery Dispatch Behind the Meter.txt
> +The dispatch options will cycle the battery if anticipated revenue exceeds the cycle degradation penalty. A higher penalty will decrease cycling, a lower penalty will increase cycling and may lead to
name also here

2020-10-20 23:11 UTC, merged