Fix scrollbar issue
NREL/SAM pull request #408
Opened 2020-10-22 10:27 UTC by sjanzou

Fixes widgets going off page bottom but resets to top of page. Cashflow also works for BOM and FOM configurations

2020-10-22 15:22 UTC, brtietz approved these changes
The fix looks great! Is there a reason to leave so much commented-out code? I generally find git history more helpful since the commit message provides good context on why things were changed or removed.

2020-10-22 16:07 UTC, mjprilliman reviewed
I'm still seeing some issues on the battery example with the bottom of the page cutting off. It seems that when you open one collapsible tab the page appropriately resizes, but upon opening a second tab the page size cuts off the bottom again and the top shifts down. 

I can note that in my testing for the ME pages programatically opening the collapsible tabs by manipulating the collapsible var used in the startup page does seem to automatically fix the page size each time. Not sure how helpful that is for the battery case but something I discovered.

2020-10-22 17:34 UTC, cpaulgilman approved these changes

2020-10-22 19:42 UTC, dguittet requested changes
Thanks for fixing it so quickly! Agree with @brtietz that unnecessary comments should be removed. If there is extra information you'd like to track, perhaps adding them as comments to this Issue / PR will be a good reference instead.

2020-10-22 19:42 UTC, dguittet commented on src/inputpage.cpp
> +//		(int)(r.width * m_scaleX), (int)(r.height * m_scaleY));
please remove unused

2020-10-22 19:42 UTC, dguittet commented on src/inputpage.cpp
> +				//if (i == 0) rct.y = 0;
please remove

2020-10-23 03:25 UTC, sjanzou commented
Changes requested made and scroll bar issue in #405 resolved.

2020-10-23 03:45 UTC, sjanzou commented
Address all issues and closes #405

2020-10-23 03:46 UTC, merged

2020-10-23 03:46 UTC, sjanzou commented
Closes #405