Fix SAM issue 393
NREL/SAM pull request #413
Opened 2020-10-29 10:36 UTC by sjanzou

Adds additional project file checks and fixes issues with duplicate parametric outputs that corrupt SAM project files

2020-10-29 15:16 UTC, brtietz requested changes
@sjanzou I think there were some merge issues here. All of the batt_replacement_schedule variables and the GUI option were removed in https://github.com/NREL/SAM/pull/409. Is there a reason they needed to come back?

2020-10-29 17:14 UTC, cpaulgilman approved these changes
This looks good Steve. I pushed a commit to revise the error message:

![image](https://user-images.githubusercontent.com/27711933/97608397-8843c700-19cf-11eb-9ea3-9a2700330b82.png)

2020-10-29 21:04 UTC, sjanzou commented
> @sjanzou I think there were some merge issues here. All of the batt_replacement_schedule variables and the GUI option were removed in #409. Is there a reason they needed to come back?

Not sure why these were updated... Seems like when I merged develop into #393 these got updated for some reason... I will remove from this pull request.

2020-10-30 05:28 UTC, sjanzou commented
Revert changes per @brtietz and run 419 tests and verify defaults and forms from develop and close #393

2020-10-30 15:16 UTC, brtietz commented
@sjanzou the state of this branch as of 52a789c looks good to me, but it didn't get merged into develop (closed instead of merged). Is that right?

2020-11-06 06:01 UTC, merged

2020-11-06 06:02 UTC, sjanzou commented
Closes #393 as before