Changed duration sizing defaults to kwh option, changed variable
NREL/SAM pull request #606
Opened 2021-05-03 19:50 UTC by mjprilliman

-Fixes lost value issue when changing between kwh and h battery sizing options
-Implements bidirectional overwrites when switching between options to keep values for each option unless manually changed
-Sets default to kwh option for all battery configurations, as this is the existing method for sizing the battery.

2021-05-03 20:06 UTC, brtietz requested changes
The functions for switching between kWh and h are working great, but my saved files from 2020.11.29r1 are still having their durations overwritten to a two hr battery. It's just displayed in kWh now.

2021-05-03 22:22 UTC, brtietz approved these changes
Looks good as of the latest commit. Thanks!

2021-05-04 05:46 UTC, sjanzou commented
@mjprilliman, pull request looks good

2021-05-04 16:39 UTC, cpaulgilman approved these changes

2021-05-04 16:48 UTC, merged