PV Smoothing to merge into develop to consolidate FOM options
NREL/SAM pull request #664
Opened 2021-07-22 10:49 UTC by sjanzou

2021-07-22 16:03 UTC, brtietz commented
Given that the weather file default in SAM is an hour I wonder if this red message should explicitly discuss a shorter timestep weather file:

![image](https://user-images.githubusercontent.com/5530592/126671009-027af8b4-9404-43e8-8424-2fcebe099867.png)

2021-07-22 16:04 UTC, mjprilliman reviewed
Fixed some issues from the integration of develop into PVSmoothing.

2021-07-22 16:04 UTC, mjprilliman commented on deploy/runtime/ui/Battery Dispatch PV Smoothing.txt
> +function toggle_dispatch_pvs()
Change toggle_dispatch to toggle_dispatch_pvs as Manual Dispatch also uses toggle_dispatch()

2021-07-22 16:04 UTC, mjprilliman commented on deploy/runtime/ui/Battery Dispatch Automated FOM.txt
> +PV smoothing
Index Labels property on variables was overwriting Object properties Items list so PV Smoothing wasn't showing up. I committed the fix to this branch

2021-07-22 16:04 UTC, mjprilliman commented on test_results_win64.csv
> +PV Battery,Single Owner,996456,103.113,9.40234,; Notice: The simple efficiency and Sandia module models do not allow limiting module voltage to the MPPT tracking range of the inverter.
Need to re-run Single Owner model as the defaults were all changed in the PVS debugging process.

2021-07-22 16:05 UTC, brtietz commented
This is the error I get when trying to select PVSmoothing on the Fuel Cell - Single Owner configuration:

![image](https://user-images.githubusercontent.com/5530592/126671400-6aca00fd-9716-4870-8660-b915d68f00ea.png)

Do we want to provide the option for that configuration or remove it?

2021-07-22 16:07 UTC, brtietz commented
Looks like there are a few issues with generic battery FOM cases as well. This is with "import hourly or subhourly generation profile" selected:

![image](https://user-images.githubusercontent.com/5530592/126671774-7d650aea-44c1-4c75-9ede-bef8608ea474.png)

2021-07-22 16:08 UTC, brtietz requested changes
Detailed PV-Battery FOM configurations look good to me. Fuel Cell and Generic System cases have some bugs with the new PV Smoothing UI.

2021-07-22 16:27 UTC, mjprilliman commented
> This is the error I get when trying to select PVSmoothing on the Fuel Cell - Single Owner configuration:
> 
> ![image](https://user-images.githubusercontent.com/5530592/126671400-6aca00fd-9716-4870-8660-b915d68f00ea.png)
> 
> Do we want to provide the option for that configuration or remove it?

Not sure on whether it should be included or not but this was a startup.lk error as the PV Smoothing form wasn't in the list for Fuel Cell FOM. I can push a fix if we do want to include this as an option

2021-07-22 16:34 UTC, mjprilliman commented
> Looks like there are a few issues with generic battery FOM cases as well. This is with "import hourly or subhourly generation profile" selected:
> 
> ![image](https://user-images.githubusercontent.com/5530592/126671774-7d650aea-44c1-4c75-9ede-bef8608ea474.png)

This stems from the ui_step_minutes calculated variable. The issue there is that when you select "import hourly or subhourly generation profile", The default for the energy_output_array variable has size 1. So is this a bug or a hint to the user that they actually need to input some sort of generation profile?

2021-07-22 18:40 UTC, cpaulgilman approved these changes
I did a little UI cleanup, including addressing @brtietz's comment about the warning message for subhourly weather data:

![image](https://user-images.githubusercontent.com/27711933/126686618-01c3c8b5-df05-4685-bfee-4134834482f8.png)

I think this option should only be available for PV Battery / Single Owner configurations for now. I could see an application for Generic Battery / Single Owner for users who want to run the model with measured output data, but this mostly seems to be a forecasting tool rather than a performance monitoring tool. For fuel cells would people expect an option to allow the fuel cell to contribute to PV ramp rate mitigation?

I pushed a change to handle that for now by displaying a UI message on Battery Dispatch Options FOM if `batt_dispatch_choice_ui = 3` when technology() != PV Battery, and come up with a better solution later.

2021-07-22 18:42 UTC, cpaulgilman commented
> 
> 
> > This is the error I get when trying to select PVSmoothing on the Fuel Cell - Single Owner configuration:
> > ![image](https://user-images.githubusercontent.com/5530592/126671400-6aca00fd-9716-4870-8660-b915d68f00ea.png)
> > Do we want to provide the option for that configuration or remove it?
> 
> Not sure on whether it should be included or not but this was a startup.lk error as the PV Smoothing form wasn't in the list for Fuel Cell FOM. I can push a fix if we do want to include this as an option

@mjprilliman Can you push a fix to add the PV smoothing UI form to Fuel Cell configurations for now? After my latest commit, if you choose PV smoothing a red warning message should display saying that PV smoothing is for PV Battery only. Otherwise we will need a different version of batt_dispatch_choice_ui for PV and non-PV battery configs.

2021-07-22 19:14 UTC, mjprilliman commented
> > > This is the error I get when trying to select PVSmoothing on the Fuel Cell - Single Owner configuration:
> > > ![image](https://user-images.githubusercontent.com/5530592/126671400-6aca00fd-9716-4870-8660-b915d68f00ea.png)
> > > Do we want to provide the option for that configuration or remove it?
> > 
> > 
> > Not sure on whether it should be included or not but this was a startup.lk error as the PV Smoothing form wasn't in the list for Fuel Cell FOM. I can push a fix if we do want to include this as an option
> 
> @mjprilliman Can you push a fix to add the PV smoothing UI form to Fuel Cell configurations for now? After my latest commit, if you choose PV smoothing a red warning message should display saying that PV smoothing is for PV Battery only. Otherwise we will need a different version of batt_dispatch_choice_ui for PV and non-PV battery configs.

@cpaulgilman This wouldn't exactly be an elegant solution but could we change the Height property on batt_dispatch_choice_ui for non PV-Battery configs so that users would never see PV Smoothing? It will not be the default for any cases so the PV Smoothing UI form would only load in the case of someone changing the value of batt_dispatch_choice_ui from the Inputs Browser, which would then be covered by your message.

2021-07-22 20:04 UTC, cpaulgilman commented
> 
> 
> > > > This is the error I get when trying to select PVSmoothing on the Fuel Cell - Single Owner configuration:
> > > > ![image](https://user-images.githubusercontent.com/5530592/126671400-6aca00fd-9716-4870-8660-b915d68f00ea.png)
> > > > Do we want to provide the option for that configuration or remove it?
> > > 
> > > 
> > > Not sure on whether it should be included or not but this was a startup.lk error as the PV Smoothing form wasn't in the list for Fuel Cell FOM. I can push a fix if we do want to include this as an option
> > 
> > 
> > @mjprilliman Can you push a fix to add the PV smoothing UI form to Fuel Cell configurations for now? After my latest commit, if you choose PV smoothing a red warning message should display saying that PV smoothing is for PV Battery only. Otherwise we will need a different version of batt_dispatch_choice_ui for PV and non-PV battery configs.
> 
> @cpaulgilman This wouldn't exactly be an elegant solution but could we change the Height property on batt_dispatch_choice_ui for non PV-Battery configs so that users would never see PV Smoothing? It will not be the default for any cases so the PV Smoothing UI form would only load in the case of someone changing the value of batt_dispatch_choice_ui from the Inputs Browser, which would then be covered by your message.

Thinking outside of the box, eh? ;)

I'm not sure that will work across operating systems because of the difference in font size. I think you could use the property() function to conditionally set the Items property of the batt_dispatch_choice widget, but then that would not be reflected in the Index Labels for that variable, so the option would appear in Parametrics and Inputs Browser. It's also a hack that might cause confusion for someone besides us down the road trying to understand how the form works..

2021-07-22 20:09 UTC, mjprilliman commented
> > > > > This is the error I get when trying to select PVSmoothing on the Fuel Cell - Single Owner configuration:
> > > > > ![image](https://user-images.githubusercontent.com/5530592/126671400-6aca00fd-9716-4870-8660-b915d68f00ea.png)
> > > > > Do we want to provide the option for that configuration or remove it?
> > > > 
> > > > 
> > > > Not sure on whether it should be included or not but this was a startup.lk error as the PV Smoothing form wasn't in the list for Fuel Cell FOM. I can push a fix if we do want to include this as an option
> > > 
> > > 
> > > @mjprilliman Can you push a fix to add the PV smoothing UI form to Fuel Cell configurations for now? After my latest commit, if you choose PV smoothing a red warning message should display saying that PV smoothing is for PV Battery only. Otherwise we will need a different version of batt_dispatch_choice_ui for PV and non-PV battery configs.
> > 
> > 
> > @cpaulgilman This wouldn't exactly be an elegant solution but could we change the Height property on batt_dispatch_choice_ui for non PV-Battery configs so that users would never see PV Smoothing? It will not be the default for any cases so the PV Smoothing UI form would only load in the case of someone changing the value of batt_dispatch_choice_ui from the Inputs Browser, which would then be covered by your message.
> 
> Thinking outside of the box, eh? ;)
> 
> I'm not sure that will work across operating systems because of the difference in font size. I think you could use the property() function to conditionally set the Items property of the batt_dispatch_choice widget, but then that would not be reflected in the Index Labels for that variable, so the option would appear in Parametrics and Inputs Browser. It's also a hack that might cause confusion for someone besides us down the road trying to understand how the form works..

@cpaulgilman Trying this with the Height property did not update the widget on the first load for whatever reason. Changing the Items property does work but I ran into the same confusion you mention. I think I will just rely on your message and leave it at that. Should I disable the PV Smoothing inputs for non PV Battery configs? Right now SAM will still run for Generic Battery or Fuel Cell and the PV Smoothing option selected, the results probably just don't make much sense

2021-07-22 20:24 UTC, sjanzou commented
I think we should disable PV Smoothing for all but detailed PV. We discussed that smoothing is only an option for PV systems. I see where smoothing may be useful for the PV Fuel Cell combo and i see some use cases for generic.

The red error message was directly from Will. Smoothing does not make sense at weather file intervals greater than 15 minutes per the EPRI meetings.

Let me know what you think and i will update the pull request.

Thanks for the detailed reviews!

2021-07-22 20:32 UTC, mjprilliman commented
@sjanzou @cpaulgilman Take a look at the latest commit and see if that is sufficient or if we need to more on non PV Battery

2021-07-22 21:59 UTC, cpaulgilman commented
> 
> 
> @sjanzou @cpaulgilman Take a look at the latest commit and see if that is sufficient or if we need to more on non PV Battery

This looks good to me. I revised the message to mention 15 minute weather data instead of 30 minutes.

2021-07-22 22:58 UTC, sjanzou commented
Looks good to me. Any other items for this pull request?

2021-07-22 23:15 UTC, mjprilliman commented
> Looks good to me. Any other items for this pull request?

Nothing from me

2021-07-22 23:45 UTC, cpaulgilman commented
> 
> 
> > Looks good to me. Any other items for this pull request?
> 
> Nothing from me

Nor from me.

2021-07-23 12:05 UTC, sjanzou commented
Generic Battery and Fuel Cell updates for FOM dispatch with PV Smoothing updated and ssc tests added and project files tested. Please recheck and let me know if you have any changes. Thanks!

2021-07-23 15:23 UTC, mjprilliman reviewed
A little confused now and what the final verdict is on the Fuel Cell FOM handling

2021-07-23 15:23 UTC, mjprilliman commented on deploy/runtime/startup.lk
> +		[{'name'='Fuel Cell Dispatch Manual', 'caption'='Manual'}],
So @cpaulgilman and I have discussed this issue. The battery manual dispatch page for fuel cell also includes the controls for fuel cell manual dispatch. So if the user selects Manual Dispatch for fuel cell dispatch but not for battery dispatch, they will not be able to see the controls for manual fuel cell dispatch. This was why the Fuel Cell Dispatch Manual was fixed as a header page.

2021-07-23 15:23 UTC, mjprilliman commented on deploy/runtime/ui/Battery Dispatch Options FOM.txt
>  		if ( technology() != 'PV Battery' )
So is the final decision to give a warning to the user that the PVSmoothing option is only intended for PV Battery configs or not?

2021-07-23 15:23 UTC, mjprilliman commented on deploy/runtime/ui/Battery Dispatch PV Smoothing.txt
>  	mode = ${batt_dispatch_choice};
If we are hard-coding this then `mode` is not needed.

2021-07-23 20:05 UTC, mjprilliman commented on test_results_win64.csv
> +PV Battery,Commercial,911877.375000,4.274710,NA,;
These are the test values that are in Patch 2. I changed the values with this commit (https://github.com/NREL/SAM/commit/6b8ebd84e106c7b5158b71d49bddbf984fbaa4c9#diff-8b237736d5563a32f81df3035be5cccb0f7b2cfd8b863b1d3d4e5956f65dfb1dR123) and must not have changed it back.

2021-07-23 21:06 UTC, brtietz approved these changes
Changes look good to me. Ok to merge, contingent on SSC issues being solved. I'm fine with resolving the manual dispatch UI form issues in another PR.

2021-07-27 06:12 UTC, merged