Removed system_use_recapitalization input for all configs except Geothermal
NREL/SAM pull request #678
Opened 2021-08-08 19:45 UTC by mjprilliman

-Closes #633

2021-08-09 07:24 UTC, sjanzou requested changes
@mjprilliman, the Travis-CI build is failing becasue the defaults are failing to run. Can you run on Windows and check in the test_results_win64.csv results and restart the Travis-CI build. If that fails, I can test on CentOS7. Thanks!

2021-08-09 13:03 UTC, mjprilliman commented
> @mjprilliman, the Travis-CI build is failing becasue the defaults are failing to run. Can you run on Windows and check in the test_results_win64.csv results and restart the Travis-CI build. If that fails, I can test on CentOS7. Thanks!

Will push that this morning! Forgot to run the results before the first commit.

2021-08-10 09:04 UTC, sjanzou commented
@mjprilliman, looks good, thanks for tackling this!

2021-08-16 14:26 UTC, tyneises approved these changes

2021-08-16 14:27 UTC, merged