ssc_auto_exec created to address #634 only works in callbacks and NOT MIMOs
NREL/SAM pull request #687
Opened 2021-08-19 11:40 UTC by sjanzou

The ssc_auto_exec works in callback scripts but not MIMOs. For example, see ETES System Design page. The issue is that equations are evaluated before the case is created and the invoke functions need to have the case to iterate over the variables. That is why the tedious MIMO method works and updates whenever any of the specified inputs are changed. Still investigating alternate solutions.

2021-08-19 14:21 UTC, tyneises requested changes
Thanks, I see the problem. The callback alternative also has this problem after the page loads - it doesn't know which variables should trigger re-evaluation of the callback. Is it possible to build a function that returns True if any variable in the cmod changes in the UI? E.g. on_change_any_cmod_input()? Or equivalently a $MIMOcmod$ that checks all cmod inputs?

2021-08-21 11:42 UTC, sjanzou commented
Search through lk parser and equation evaluator and setting of inputs and output and dependent varibles and find no lk function that will properly setup and parse equations in Case->SetConfiguration.

Alternative is to parse the equation script at input page load and expand as 
![image](https://user-images.githubusercontent.com/6498311/130320620-9af83ae2-8019-4e22-bce0-8c63e7269e25.png)
For proper triggering when a MIMO input changes.

Cannot handle the if financing exception above but all other values can be set and the data opject can be created and returned and all will be treated as inputs.

Change would have to occur either at 
![image](https://user-images.githubusercontent.com/6498311/130320633-83d7be7f-b73d-409b-80d6-f47a9284587f.png)
or at
![image](https://user-images.githubusercontent.com/6498311/130320638-1a214eb8-02a8-4ffa-a422-934b0d7a5552.png)

2021-08-24 11:17 UTC, sjanzou commented
@tyneises , working now in equations in SAM_634 branches of lk, ssc, and SAM. SSC variables not in UI need to have UIHINT set to SIMULATION_PARAMETER
![image](https://user-images.githubusercontent.com/6498311/130607557-d143cfe5-ba4f-4e9f-9f64-0fb6678f072e.png)

2021-08-24 16:10 UTC, tyneises approved these changes
This is really great! Is there a way to determine whether the input is a SIMULATION_PARAMETER based on the value on the financial model type, like how "required_if" works? It would be convenient to eliminate the if(financial_model) logic in the MIMO on the System Design page.

2021-08-26 06:42 UTC, merged