Battery UI fixes
NREL/SAM pull request #806
Opened 2021-11-24 20:31 UTC by mjprilliman

## Description

- Disable minimum time at charge state for Standalone Battery (unclear why)
- Generic Battery disabling for Automated dispatch custom weather file (similar to Standalone battery)
- Generic Battery msgbox for PVSmoothing
- 
Fixes #798 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2021-11-28 23:28 UTC, cpaulgilman requested changes
I revised the UI message text and set them up to display on_change and on_load.

I'm getting callback errors "attempting to set 'batt_C_rate' (number) to <null>" and sometimes a crash when I change battery type and choose replace defaults option for LFP/Graphite, LMO/LTO, Lead Acid...

2021-11-29 13:15 UTC, dguittet commented on deploy/runtime/ui/Battery Model.txt
> -	if (cell_params.voltage_choice == 0) {
This `if` statement needs to be reinstated. The JSON files do not contain both voltage table data and electrochemical data.

2021-11-29 22:31 UTC, cpaulgilman approved these changes
Looks good after my latest commit to re-enable minimum time at charge state per @brtietz comment, fixes to use consistent specify ppa price/irr messages for standalone and non-standalone FOM batteries, and minor line spacing in message boxes.

2021-11-30 08:35 UTC, dguittet approved these changes

2021-11-30 16:23 UTC, mjprilliman commented
Test results were the same outside of ETES (is there variation in the optimizer?). Merging this PR.

2021-11-30 16:23 UTC, merged